
# All comments are stripped out with yamlreader
# Cannot use '&' anchors and '*' aliases in separate yaml files but they will work in same yaml file with yamlreader but actual anchor/alias will be stripped out in final dict
--- # Directives above and Content below and indicates start of document
hosts:
- &esx01
  name: &esx01_name <esx01_hostname>
  hostname: *esx01_name
  remote_mgmt:
    hostname: &esx01_mgmt_name esx01_hostname-mgmt
    ip: x.x.x.x
    subnetMask: x.x.x.x
    gateway: x.x.x.x
    dns:
      server01:
      server02:
... # End of document content